application: recipe-monger
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: "2.6"
- name: lxml
  version: "2.3"

handlers:
- url: /css
  static_dir: css

- url: /less
  static_dir: less

- url: /js
  static_dir: js

- url: /.*
  script: main.app

# vim: ts=4 sw=4
